FROM mcr.microsoft.com/devcontainers/base:alpine

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Registry version — update this ARG to upgrade
ARG REGISTRY_VERSION

# Trivy version — update this ARG to upgrade
# Check release https://github.com/aquasecurity/trivy/releases
ARG TRIVY_VERSION

# Install Python + deps
RUN apk add --no-cache \
    git \
    envsubst \
    curl \
    skopeo \
    nodejs \
    npm

WORKDIR /usr/src

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

ENV DATA_DIR=/home/vscode/.local/portalcrane

# Download and install registry binary
RUN curl -L https://github.com/distribution/distribution/releases/download/v${REGISTRY_VERSION}/registry_${REGISTRY_VERSION}_linux_amd64.tar.gz \
    | tar xz -C /usr/local/bin registry
RUN --mount=type=bind,source=./docker/registry-config.yml.tpl,target=/tmp/registry-config.yml.tpl \
    mkdir -p /etc/registry && \
    envsubst < /tmp/registry-config.yml.tpl > /etc/registry/config.yml


# Download and install Trivy binary
RUN curl -L https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz \
    | tar xz -C /usr/local/bin trivy

# Angular CLI
RUN npm install -g @angular/cli

USER vscode

ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy
ENV VIRTUAL_ENV="/home/vscode/.local/venv"
RUN --mount=type=bind,source=.python-version,target=.python-version \
    uv python install \
    && uv venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

WORKDIR /workspaces

# Install Python dependencies from requirements
RUN --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv pip install -r pyproject.toml && \
    uv pip install --group dev -r pyproject.toml

# Set the default shell to bash instead of sh
ENV SHELL=/bin/bash
